##
# @description Docker services
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##
services:
  app:
      build:
          context: .
      network_mode: host
      volumes:
          - ./src:/home/dev/app/src
      working_dir: /home/dev/app/src
      environment:
          - DANGEROUSLY_OMIT_AUTH=1
      command: /bin/sleep infinity
